version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_PROGRESS=plain
    ports:
      - "26396:4321"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AUTH_SECRET=${AUTH_SECRET}
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - PYTHONIOENCODING=utf-8
    command: pnpm start
    network_mode: bridge

x-build-options: &build-options
  context: .
  dockerfile: Dockerfile
  args:
    BUILDKIT_PROGRESS: plain
  x-bake:
    platforms:
      - linux/amd64
    cache-from:
      - type=local,src=/tmp/.buildx-cache
    cache-to:
      - type=local,dest=/tmp/.buildx-cache-new,mode=max